# fly.toml app configuration file generated for ceniteg on 2024-07-15T17:31:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ceniteg'
primary_region = 'scl'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
